//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dotnetydd.OtlpDevDashboard.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Columns {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Columns() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dotnetydd.OtlpDevDashboard.Resources.Columns", typeof(Columns).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        public static string EndpointsColumnDisplayNone {
            get {
                return ResourceManager.GetString("EndpointsColumnDisplayNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Starting... 的本地化字符串。
        /// </summary>
        public static string EndpointsColumnDisplayPlaceholder {
            get {
                return ResourceManager.GetString("EndpointsColumnDisplayPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Container ID: {0} 的本地化字符串。
        /// </summary>
        public static string ResourceNameDisplayContainerIdText {
            get {
                return ResourceManager.GetString("ResourceNameDisplayContainerIdText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy container ID to clipboard 的本地化字符串。
        /// </summary>
        public static string ResourceNameDisplayCopyContainerIdText {
            get {
                return ResourceManager.GetString("ResourceNameDisplayCopyContainerIdText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process ID: {0} 的本地化字符串。
        /// </summary>
        public static string ResourceNameDisplayProcessIdText {
            get {
                return ResourceManager.GetString("ResourceNameDisplayProcessIdText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Container args 的本地化字符串。
        /// </summary>
        public static string SourceColumnDisplayContainerArgsTitle {
            get {
                return ResourceManager.GetString("SourceColumnDisplayContainerArgsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Command: {0} 的本地化字符串。
        /// </summary>
        public static string SourceColumnDisplayContainerCommand {
            get {
                return ResourceManager.GetString("SourceColumnDisplayContainerCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Container command 的本地化字符串。
        /// </summary>
        public static string SourceColumnDisplayContainerCommandTitle {
            get {
                return ResourceManager.GetString("SourceColumnDisplayContainerCommandTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Port: {0} 的本地化字符串。
        /// </summary>
        public static string SourceColumnDisplayPort {
            get {
                return ResourceManager.GetString("SourceColumnDisplayPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ports: {0} 的本地化字符串。
        /// </summary>
        public static string SourceColumnDisplayPorts {
            get {
                return ResourceManager.GetString("SourceColumnDisplayPorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Working directory: {0} 的本地化字符串。
        /// </summary>
        public static string SourceColumnDisplayWorkingDirectory {
            get {
                return ResourceManager.GetString("SourceColumnDisplayWorkingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy image name and tag to clipboard 的本地化字符串。
        /// </summary>
        public static string SourceColumnSourceCopyContainerToClipboard {
            get {
                return ResourceManager.GetString("SourceColumnSourceCopyContainerToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy file path to clipboard 的本地化字符串。
        /// </summary>
        public static string SourceColumnSourceCopyFullPathToClipboard {
            get {
                return ResourceManager.GetString("SourceColumnSourceCopyFullPathToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} error log 的本地化字符串。
        /// </summary>
        public static string UnreadLogErrorsBadgeErrorLog {
            get {
                return ResourceManager.GetString("UnreadLogErrorsBadgeErrorLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} error logs 的本地化字符串。
        /// </summary>
        public static string UnreadLogErrorsBadgeErrorLogs {
            get {
                return ResourceManager.GetString("UnreadLogErrorsBadgeErrorLogs", resourceCulture);
            }
        }
    }
}
