//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dotnetydd.OtlpDevDashboard.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConsoleLogs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConsoleLogs() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dotnetydd.OtlpDevDashboard.Resources.ConsoleLogs", typeof(ConsoleLogs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to initialize 的本地化字符串。
        /// </summary>
        public static string ConsoleLogsFailedToInitialize {
            get {
                return ResourceManager.GetString("ConsoleLogsFailedToInitialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Finished watching logs 的本地化字符串。
        /// </summary>
        public static string ConsoleLogsFinishedWatchingLogs {
            get {
                return ResourceManager.GetString("ConsoleLogsFinishedWatchingLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Console logs 的本地化字符串。
        /// </summary>
        public static string ConsoleLogsHeader {
            get {
                return ResourceManager.GetString("ConsoleLogsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initializing log viewer... 的本地化字符串。
        /// </summary>
        public static string ConsoleLogsInitializingLogViewer {
            get {
                return ResourceManager.GetString("ConsoleLogsInitializingLogViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading resources ... 的本地化字符串。
        /// </summary>
        public static string ConsoleLogsLoadingResources {
            get {
                return ResourceManager.GetString("ConsoleLogsLoadingResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logs not yet available 的本地化字符串。
        /// </summary>
        public static string ConsoleLogsLogsNotYetAvailable {
            get {
                return ResourceManager.GetString("ConsoleLogsLogsNotYetAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No resource selected 的本地化字符串。
        /// </summary>
        public static string ConsoleLogsNoResourceSelected {
            get {
                return ResourceManager.GetString("ConsoleLogsNoResourceSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} console logs 的本地化字符串。
        /// </summary>
        public static string ConsoleLogsPageTitle {
            get {
                return ResourceManager.GetString("ConsoleLogsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a resource 的本地化字符串。
        /// </summary>
        public static string ConsoleLogsSelectAResource {
            get {
                return ResourceManager.GetString("ConsoleLogsSelectAResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown state 的本地化字符串。
        /// </summary>
        public static string ConsoleLogsUnknownState {
            get {
                return ResourceManager.GetString("ConsoleLogsUnknownState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Watching logs... 的本地化字符串。
        /// </summary>
        public static string ConsoleLogsWatchingLogs {
            get {
                return ResourceManager.GetString("ConsoleLogsWatchingLogs", resourceCulture);
            }
        }
    }
}
