//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dotnetydd.OtlpDevDashboard.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ControlsStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ControlsStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dotnetydd.OtlpDevDashboard.Resources.ControlsStrings", typeof(ControlsStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 All 的本地化字符串。
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All tags 的本地化字符串。
        /// </summary>
        public static string ChartContainerAllTags {
            get {
                return ResourceManager.GetString("ChartContainerAllTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filtered tags 的本地化字符串。
        /// </summary>
        public static string ChartContainerFilteredTags {
            get {
                return ResourceManager.GetString("ChartContainerFilteredTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filters 的本地化字符串。
        /// </summary>
        public static string ChartContainerFiltersHeader {
            get {
                return ResourceManager.GetString("ChartContainerFiltersHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Options 的本地化字符串。
        /// </summary>
        public static string ChartContainerOptionsHeader {
            get {
                return ResourceManager.GetString("ChartContainerOptionsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select filters 的本地化字符串。
        /// </summary>
        public static string ChartContainerSelectFilters {
            get {
                return ResourceManager.GetString("ChartContainerSelectFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show count 的本地化字符串。
        /// </summary>
        public static string ChartContainerShowCountLabel {
            get {
                return ResourceManager.GetString("ChartContainerShowCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to display chart 的本地化字符串。
        /// </summary>
        public static string ChartContainerUnableToDisplay {
            get {
                return ResourceManager.GetString("ChartContainerUnableToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show all 的本地化字符串。
        /// </summary>
        public static string EnvironmentVariablesFilterToggleShowAll {
            get {
                return ResourceManager.GetString("EnvironmentVariablesFilterToggleShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show spec only 的本地化字符串。
        /// </summary>
        public static string EnvironmentVariablesFilterToggleShowSpecOnly {
            get {
                return ResourceManager.GetString("EnvironmentVariablesFilterToggleShowSpecOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide values 的本地化字符串。
        /// </summary>
        public static string EnvironmentVariablesHideVariableValues {
            get {
                return ResourceManager.GetString("EnvironmentVariablesHideVariableValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show values 的本地化字符串。
        /// </summary>
        public static string EnvironmentVariablesShowVariableValues {
            get {
                return ResourceManager.GetString("EnvironmentVariablesShowVariableValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter... 的本地化字符串。
        /// </summary>
        public static string FilterPlaceholder {
            get {
                return ResourceManager.GetString("FilterPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy to clipboard 的本地化字符串。
        /// </summary>
        public static string GridValueCopyToClipboard {
            get {
                return ResourceManager.GetString("GridValueCopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide value 的本地化字符串。
        /// </summary>
        public static string GridValueMaskHideValue {
            get {
                return ResourceManager.GetString("GridValueMaskHideValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show value 的本地化字符串。
        /// </summary>
        public static string GridValueMaskShowValue {
            get {
                return ResourceManager.GetString("GridValueMaskShowValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string NameColumnHeader {
            get {
                return ResourceManager.GetString("NameColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Count 的本地化字符串。
        /// </summary>
        public static string PlotlyChartCount {
            get {
                return ResourceManager.GetString("PlotlyChartCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Length 的本地化字符串。
        /// </summary>
        public static string PlotlyChartLength {
            get {
                return ResourceManager.GetString("PlotlyChartLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value 的本地化字符串。
        /// </summary>
        public static string PlotlyChartValue {
            get {
                return ResourceManager.GetString("PlotlyChartValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value 的本地化字符串。
        /// </summary>
        public static string PropertyGridValueColumnHeader {
            get {
                return ResourceManager.GetString("PropertyGridValueColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select an application 的本地化字符串。
        /// </summary>
        public static string SelectAnApplication {
            get {
                return ResourceManager.GetString("SelectAnApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duration &lt;strong&gt;{0}&lt;/strong&gt; 的本地化字符串。
        /// </summary>
        public static string SpanDetailsDuration {
            get {
                return ResourceManager.GetString("SpanDetailsDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Service &lt;strong&gt;{0}&lt;/strong&gt; 的本地化字符串。
        /// </summary>
        public static string SpanDetailsService {
            get {
                return ResourceManager.GetString("SpanDetailsService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start time &lt;strong&gt;{0}&lt;/strong&gt; 的本地化字符串。
        /// </summary>
        public static string SpanDetailsStartTime {
            get {
                return ResourceManager.GetString("SpanDetailsStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string SummaryDetailsViewCloseView {
            get {
                return ResourceManager.GetString("SummaryDetailsViewCloseView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Split horizontal 的本地化字符串。
        /// </summary>
        public static string SummaryDetailsViewSplitHorizontal {
            get {
                return ResourceManager.GetString("SummaryDetailsViewSplitHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Split vertical 的本地化字符串。
        /// </summary>
        public static string SummaryDetailsViewSplitVertical {
            get {
                return ResourceManager.GetString("SummaryDetailsViewSplitVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total: &lt;strong&gt;{0} results found&lt;/strong&gt; 的本地化字符串。
        /// </summary>
        public static string TotalItemsFooterText {
            get {
                return ResourceManager.GetString("TotalItemsFooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View 的本地化字符串。
        /// </summary>
        public static string ViewAction {
            get {
                return ResourceManager.GetString("ViewAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View logs 的本地化字符串。
        /// </summary>
        public static string ViewLogsLink {
            get {
                return ResourceManager.GetString("ViewLogsLink", resourceCulture);
            }
        }
    }
}
