//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dotnetydd.OtlpDashboard.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Dialogs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dialogs() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dotnetydd.OtlpDashboard.Resources.Dialogs", typeof(Dialogs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Apply filter 的本地化字符串。
        /// </summary>
        public static string FilterDialogApplyFilterButtonText {
            get {
                return ResourceManager.GetString("FilterDialogApplyFilterButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string FilterDialogCancelButtonText {
            get {
                return ResourceManager.GetString("FilterDialogCancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a filter condition 的本地化字符串。
        /// </summary>
        public static string FilterDialogConditionSelectLabel {
            get {
                return ResourceManager.GetString("FilterDialogConditionSelectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Field 的本地化字符串。
        /// </summary>
        public static string FilterDialogFieldPlaceholder {
            get {
                return ResourceManager.GetString("FilterDialogFieldPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove filter 的本地化字符串。
        /// </summary>
        public static string FilterDialogRemoveFilterButtonText {
            get {
                return ResourceManager.GetString("FilterDialogRemoveFilterButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value 的本地化字符串。
        /// </summary>
        public static string FilterDialogTextValuePlaceholder {
            get {
                return ResourceManager.GetString("FilterDialogTextValuePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark 的本地化字符串。
        /// </summary>
        public static string SettingsDialogDarkTheme {
            get {
                return ResourceManager.GetString("SettingsDialogDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light 的本地化字符串。
        /// </summary>
        public static string SettingsDialogLightTheme {
            get {
                return ResourceManager.GetString("SettingsDialogLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System 的本地化字符串。
        /// </summary>
        public static string SettingsDialogSystemTheme {
            get {
                return ResourceManager.GetString("SettingsDialogSystemTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Theme 的本地化字符串。
        /// </summary>
        public static string SettingsDialogTheme {
            get {
                return ResourceManager.GetString("SettingsDialogTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version: {0} 的本地化字符串。
        /// </summary>
        public static string SettingsDialogVersion {
            get {
                return ResourceManager.GetString("SettingsDialogVersion", resourceCulture);
            }
        }
    }
}
