//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dotnetydd.OtlpDevDashboard.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Layout {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Layout() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dotnetydd.OtlpDevDashboard.Resources.Layout", typeof(Layout).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Help 的本地化字符串。
        /// </summary>
        public static string MainLayoutAspireDashboardHelpLink {
            get {
                return ResourceManager.GetString("MainLayoutAspireDashboardHelpLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 .NET Aspire repo 的本地化字符串。
        /// </summary>
        public static string MainLayoutAspireRepoLink {
            get {
                return ResourceManager.GetString("MainLayoutAspireRepoLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} dashboard 的本地化字符串。
        /// </summary>
        public static string MainLayoutDashboardName {
            get {
                return ResourceManager.GetString("MainLayoutDashboardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Launch settings 的本地化字符串。
        /// </summary>
        public static string MainLayoutLaunchSettings {
            get {
                return ResourceManager.GetString("MainLayoutLaunchSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string MainLayoutSettingsDialogClose {
            get {
                return ResourceManager.GetString("MainLayoutSettingsDialogClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string MainLayoutSettingsDialogTitle {
            get {
                return ResourceManager.GetString("MainLayoutSettingsDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An unhandled error has occurred. 的本地化字符串。
        /// </summary>
        public static string MainLayoutUnhandledErrorMessage {
            get {
                return ResourceManager.GetString("MainLayoutUnhandledErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reload 的本地化字符串。
        /// </summary>
        public static string MainLayoutUnhandledErrorReload {
            get {
                return ResourceManager.GetString("MainLayoutUnhandledErrorReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Console logs 的本地化字符串。
        /// </summary>
        public static string NavMenuConsoleLogsTab {
            get {
                return ResourceManager.GetString("NavMenuConsoleLogsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Metrics 的本地化字符串。
        /// </summary>
        public static string NavMenuMetricsTab {
            get {
                return ResourceManager.GetString("NavMenuMetricsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Monitoring 的本地化字符串。
        /// </summary>
        public static string NavMenuMonitoringTab {
            get {
                return ResourceManager.GetString("NavMenuMonitoringTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resources 的本地化字符串。
        /// </summary>
        public static string NavMenuResourcesTab {
            get {
                return ResourceManager.GetString("NavMenuResourcesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Structured logs 的本地化字符串。
        /// </summary>
        public static string NavMenuStructuredLogsTab {
            get {
                return ResourceManager.GetString("NavMenuStructuredLogsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Traces 的本地化字符串。
        /// </summary>
        public static string NavMenuTracesTab {
            get {
                return ResourceManager.GetString("NavMenuTracesTab", resourceCulture);
            }
        }
    }
}
