//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dotnetydd.OtlpDevDashboard.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Metrics {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Metrics() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dotnetydd.OtlpDevDashboard.Resources.Metrics", typeof(Metrics).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Metrics 的本地化字符串。
        /// </summary>
        public static string MetricsHeader {
            get {
                return ResourceManager.GetString("MetricsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last 15 minutes 的本地化字符串。
        /// </summary>
        public static string MetricsLastFifteenMinutes {
            get {
                return ResourceManager.GetString("MetricsLastFifteenMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last 5 minutes 的本地化字符串。
        /// </summary>
        public static string MetricsLastFiveMinutes {
            get {
                return ResourceManager.GetString("MetricsLastFiveMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last hour 的本地化字符串。
        /// </summary>
        public static string MetricsLastHour {
            get {
                return ResourceManager.GetString("MetricsLastHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last 1 minute 的本地化字符串。
        /// </summary>
        public static string MetricsLastOneMinute {
            get {
                return ResourceManager.GetString("MetricsLastOneMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last 6 hours 的本地化字符串。
        /// </summary>
        public static string MetricsLastSixHours {
            get {
                return ResourceManager.GetString("MetricsLastSixHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last 30 minutes 的本地化字符串。
        /// </summary>
        public static string MetricsLastThirtyMinutes {
            get {
                return ResourceManager.GetString("MetricsLastThirtyMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last 3 hours 的本地化字符串。
        /// </summary>
        public static string MetricsLastThreeHours {
            get {
                return ResourceManager.GetString("MetricsLastThreeHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last 12 hours 的本地化字符串。
        /// </summary>
        public static string MetricsLastTwelveHours {
            get {
                return ResourceManager.GetString("MetricsLastTwelveHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last 24 hours 的本地化字符串。
        /// </summary>
        public static string MetricsLastTwentyFourHours {
            get {
                return ResourceManager.GetString("MetricsLastTwentyFourHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No metrics for the selected resource 的本地化字符串。
        /// </summary>
        public static string MetricsNoMetricsForResource {
            get {
                return ResourceManager.GetString("MetricsNoMetricsForResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} metrics 的本地化字符串。
        /// </summary>
        public static string MetricsPageTitle {
            get {
                return ResourceManager.GetString("MetricsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a duration 的本地化字符串。
        /// </summary>
        public static string MetricsSelectADuration {
            get {
                return ResourceManager.GetString("MetricsSelectADuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a resource to view metrics 的本地化字符串。
        /// </summary>
        public static string MetricsSelectAResource {
            get {
                return ResourceManager.GetString("MetricsSelectAResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select instrument. 的本地化字符串。
        /// </summary>
        public static string MetricsSelectInstrument {
            get {
                return ResourceManager.GetString("MetricsSelectInstrument", resourceCulture);
            }
        }
    }
}
