//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dotnetydd.OtlpDashboard.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dotnetydd.OtlpDashboard.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Endpoints 的本地化字符串。
        /// </summary>
        public static string ResourcesEnvironmentVariablesGridEndpointsColumnHeader {
            get {
                return ResourceManager.GetString("ResourcesEnvironmentVariablesGridEndpointsColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Environment 的本地化字符串。
        /// </summary>
        public static string ResourcesEnvironmentVariablesGridEnvironmentColumnHeader {
            get {
                return ResourceManager.GetString("ResourcesEnvironmentVariablesGridEnvironmentColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name (ID) 的本地化字符串。
        /// </summary>
        public static string ResourcesEnvironmentVariablesGridNameColumnHeader {
            get {
                return ResourceManager.GetString("ResourcesEnvironmentVariablesGridNameColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Source 的本地化字符串。
        /// </summary>
        public static string ResourcesEnvironmentVariablesGridSourceColumnHeader {
            get {
                return ResourceManager.GetString("ResourcesEnvironmentVariablesGridSourceColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start time 的本地化字符串。
        /// </summary>
        public static string ResourcesEnvironmentVariablesGridStartTimeColumnHeader {
            get {
                return ResourceManager.GetString("ResourcesEnvironmentVariablesGridStartTimeColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 State 的本地化字符串。
        /// </summary>
        public static string ResourcesEnvironmentVariablesGridStateColumnHeader {
            get {
                return ResourceManager.GetString("ResourcesEnvironmentVariablesGridStateColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Environment variables for {0} 的本地化字符串。
        /// </summary>
        public static string ResourcesEnvironmentVariablesHeader {
            get {
                return ResourceManager.GetString("ResourcesEnvironmentVariablesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resources 的本地化字符串。
        /// </summary>
        public static string ResourcesHeader {
            get {
                return ResourceManager.GetString("ResourcesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No environment variables 的本地化字符串。
        /// </summary>
        public static string ResourcesNoEnvironmentVariables {
            get {
                return ResourceManager.GetString("ResourcesNoEnvironmentVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No resources found 的本地化字符串。
        /// </summary>
        public static string ResourcesNoResources {
            get {
                return ResourceManager.GetString("ResourcesNoResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} resources 的本地化字符串。
        /// </summary>
        public static string ResourcesPageTitle {
            get {
                return ResourceManager.GetString("ResourcesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resource types 的本地化字符串。
        /// </summary>
        public static string ResourcesResourceTypesHeader {
            get {
                return ResourceManager.GetString("ResourcesResourceTypesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type filter: All types visible 的本地化字符串。
        /// </summary>
        public static string ResourcesTypeFilterAllVisible {
            get {
                return ResourceManager.GetString("ResourcesTypeFilterAllVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type filter: Filtered 的本地化字符串。
        /// </summary>
        public static string ResourcesTypeFiltered {
            get {
                return ResourceManager.GetString("ResourcesTypeFiltered", resourceCulture);
            }
        }
    }
}
