//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dotnetydd.OtlpDashboard.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StructuredLogs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StructuredLogs() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dotnetydd.OtlpDashboard.Resources.StructuredLogs", typeof(StructuredLogs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Add filter 的本地化字符串。
        /// </summary>
        public static string StructuredLogsAddFilter {
            get {
                return ResourceManager.GetString("StructuredLogsAddFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All 的本地化字符串。
        /// </summary>
        public static string StructuredLogsAllTypes {
            get {
                return ResourceManager.GetString("StructuredLogsAllTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Details 的本地化字符串。
        /// </summary>
        public static string StructuredLogsDetailsColumnHeader {
            get {
                return ResourceManager.GetString("StructuredLogsDetailsColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit filter 的本地化字符串。
        /// </summary>
        public static string StructuredLogsEditFilter {
            get {
                return ResourceManager.GetString("StructuredLogsEditFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log entry details 的本地化字符串。
        /// </summary>
        public static string StructuredLogsEntryDetails {
            get {
                return ResourceManager.GetString("StructuredLogsEntryDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filters:  的本地化字符串。
        /// </summary>
        public static string StructuredLogsFilters {
            get {
                return ResourceManager.GetString("StructuredLogsFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Structured logs 的本地化字符串。
        /// </summary>
        public static string StructuredLogsHeader {
            get {
                return ResourceManager.GetString("StructuredLogsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Level 的本地化字符串。
        /// </summary>
        public static string StructuredLogsLevelColumnHeader {
            get {
                return ResourceManager.GetString("StructuredLogsLevelColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message 的本地化字符串。
        /// </summary>
        public static string StructuredLogsMessageColumnHeader {
            get {
                return ResourceManager.GetString("StructuredLogsMessageColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message filter 的本地化字符串。
        /// </summary>
        public static string StructuredLogsMessageFilter {
            get {
                return ResourceManager.GetString("StructuredLogsMessageFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimum log level filter 的本地化字符串。
        /// </summary>
        public static string StructuredLogsMinimumLogFilter {
            get {
                return ResourceManager.GetString("StructuredLogsMinimumLogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No filters 的本地化字符串。
        /// </summary>
        public static string StructuredLogsNoFilters {
            get {
                return ResourceManager.GetString("StructuredLogsNoFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No structured logs found 的本地化字符串。
        /// </summary>
        public static string StructuredLogsNoLogsFound {
            get {
                return ResourceManager.GetString("StructuredLogsNoLogsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} structured logs 的本地化字符串。
        /// </summary>
        public static string StructuredLogsPageTitle {
            get {
                return ResourceManager.GetString("StructuredLogsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resource 的本地化字符串。
        /// </summary>
        public static string StructuredLogsResourceColumnHeader {
            get {
                return ResourceManager.GetString("StructuredLogsResourceColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a minimum log level 的本地化字符串。
        /// </summary>
        public static string StructuredLogsSelectMinimumLogLevel {
            get {
                return ResourceManager.GetString("StructuredLogsSelectMinimumLogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timestamp 的本地化字符串。
        /// </summary>
        public static string StructuredLogsTimestampColumnHeader {
            get {
                return ResourceManager.GetString("StructuredLogsTimestampColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trace 的本地化字符串。
        /// </summary>
        public static string StructuredLogsTraceColumnHeader {
            get {
                return ResourceManager.GetString("StructuredLogsTraceColumnHeader", resourceCulture);
            }
        }
    }
}
